---
droplet_name: <CHANGE ME>
droplet_region_id: nyc3
droplet_size_id: 2gb
droplet_image_id: ubuntu-19-04-x64

users:
  - username: <CHANGE ME>
    name: <CHANGE ME>
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/<CHANGE ME>.pub') }}"
    shell: /bin/bash
    password: '{% if user_acct_password is defined %}{{ user_acct_password | password_hash("sha512") }}{% else %}{{ None }}{% endif %}'
    update_password: on_create
    groups:
      - sudo

swapfile_size: 4096
swapfile_swappiness: 10
swapfile_vfs_cache_pressure: 100

ntp_timezone: Etc/UTC
ntp_manage_config: true

sshd:
  PermitRootLogin: no
  PasswordAuthentication: no

ufw_rules:
  - { port: 22, rule: allow }
  - { port: 80, rule: allow }
  - { port: 443, rule: allow }
ufw_default_forward_policy: ACCEPT
ufw_logging: full
ufw_applications:
  - { name: "OpenSSH" }
ufw_reset: no

# apt package
docker_package: docker-ce
# pip dependencies
docker_pip_dependencies:
 - docker-py
# start on boot
docker_service_enabled: yes
# current state: started, stopped
docker_service_state: started
# docker default options
docker_options: []
# list of images (http://docs.ansible.com/docker_image_module.html)
docker_images: []
# list of containers (http://docs.ansible.com/docker_module.html)
docker_containers: []